### ISSUE TITLE
Proper way to setup IPC?

### ISSUE THREAD

**Issue by zelik888** [davebeyer/homebridge-lutron-hwi#3]
I have 200 Lutron circuits so I need to split to multiple processes. It's not clear how to do so? I've listed my config below. This seems to work but homebridge pops up with an error saying this method will be deprecated in future ("The dynamic platform lutron-hwi from the plugin @davebeyer/homebridge-lutron-hwi seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!")

 Or do I need multiple homebridge running? 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
        {
            "name": "Lutron Lighting 1F-2F",
            "circuitsFile": "/homebridge/lighting-1F2F.json",
            "commMode": "telnet",
            "telnetIP": "192.168.1.14",
            "telnetPort": 3000,
            "minInterCmdTime": 100,
            "disabled": false,
            "platform": "lutron-hwi"
        },
        {
            "name": "Lutron Lighting Bridge B1",
            "circuitsFile": "/homebridge/lighting-B1.json",
            "commMode": "ipc",
            "minInterCmdTime": 200,
            "disabled": false,
            "platform": "lutron-hwi",
            "_bridge": {
                "username": "0E:83:FD:29:58:C9",
                "port": 55197
            }
        },
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.0.04
* **Homebridge Version**: 1.4
* **Node.js Version**: [v16.14.2](https://git.io/JTKEF)
* **NPM Version**: v8.5.0
* **Operating System**: Ubuntu Bionic Beaver (18.04.6 LTS)

**Comment by davebeyer** [comment]
Hi, did you notice this paragraph in the README?

> Note that due to a HomeKit limitation, Homebridge limits each bridge to 149 accessories (i.e., lighting circuits). If you have more than that, you'll need to [create multiple bridges](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#multiple-instances) to keep below this limit. In this case, separate the circuits into two or more files, one for each homebridge process.

This worked for me (I also have over 149 circuits).

**Comment by zelik888** [comment]
First: thank you for the plugin, it's awesome!!
Second: Yes, I did, and I guess my question wasn't clear. If i setup multiple homebridge instances, how do I connect IPC? Do I not fill in the telnet address? Or same IP? My current setup works but I'm just not sure i'm doing it the right way.

**Comment by davebeyer** [comment]
Thanks for the kind words, glad the plugin is helpful to you!    I have two config files (one for each Homebridge instance).    Here are some relevant lines from each.

Config file for first instance of Homebridge:

```
{
    "bridge": {
        "name": "Homebridge on RaspberryPi",
        "port": 51662,
        ...
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config",
            ...
        },
        {
            "name": "Lighting Bridge 1",
            "circuitsFile": "/absolute/path/to/circuits1.json",
            "commMode": "telnet",
            "telnetIP": "192.168.1.xyz",
            "telnetPort": 2101,
            "minInterCmdTime": 350,
            "disabled": false,
            "platform": "lutron-hwi"
        }
    ]
}
```

Config file for second instance of Homebridge (telnetIP and telnetPort are ignored when commMode is set to 'ipc'):

```
{
    "bridge": {
        "name": "Homebridge2 on RaspberryPi",
        "port": 51578,
        ...
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8582,
            "platform": "config",
            ...
        },
        {
            "name": "Lighting Bridge 2",
            "circuitsFile": "/absolute/path/to/circuits2.json",
            "commMode": "ipc",
            "minInterCmdTime": 350,
            "disabled": false,
            "platform": "lutron-hwi"
        }
    ]
}
```

**Comment by zelik888** [comment]
So ipc connects to homework’s telnet up and port as well?

**Comment by davebeyer** [comment]
Sorry for the confusion, I've edited my response above to make it clear that telnetIP and telnetPort config settings are ignored when commMode is set to 'ipc'.

**Comment by davebeyer** [comment]
Hi @zelik888, is the IPC mode now working to support your second Homebridge instance?  (If so, I'll close this issue.)

**Comment by zelik888** [comment]
It's working, I've not used a second instance (just same instance two childbridge)..not recommended but I'm lazy to make any changes as it works for now. I just wasn't sure how IPC worked without entering a IP for it to connect to

**Comment by davebeyer** [comment]
Totally get the lazy reasoning :-)

> I just wasn't sure how IPC worked without entering a IP for it to connect to

Ok, in case it wasn't clear, the second (and third...) Homebridge instances must use the "ipc" communications mode and must be running on the same server machine as the first instance.  Then they use an inter-process communications channel (currently using the fixed IPC identifier "homebridge_lutron_hwi" ... in a future release this may become configurable), so no IP address is needed for instances other than the first.

From the README:

> One Homebridge process must provide the Telnet connection to the Lutron processor. Any others (running on the same machine) must use IPC to share access to this telnet channel.
